### ISSUE TITLE
Bug: when i give lesson a name and press ok the app crashed

### ISSUE THREAD

**Issue by darewealth** [dfrits/MobilePauker2#5]
### Describe the bug.

The app crashed when I 'Give the lesson a name' and press ok

### Steps to reproduce.

* Launch the app

* Click on Add new card

* Add the front and back card and click ok 

* Then press phone back button to go back to main menu 

* Click on save icon and give the lesson a name

* Then save

### Expected Behaviour
I expected to give the lesson a name successfully and  not a crash

### Screen recording
https://youtu.be/CdQl-Ds8y_E

### Devices and Versions)

* Device: [Gionee]

* Version [7.0]

* App version [1.1.0]

### Log.
```05-12 09:48:47.987 14713 14713 E AndroidRuntime: FATAL EXCEPTION: main
05-12 09:48:47.987 14713 14713 E AndroidRuntime: Process: com.daniel.mobilepauker2, PID: 14713
05-12 09:48:47.987 14713 14713 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=null} to activity {com.daniel.mobilepauker2/com.daniel.mobilepauker2.activities.MainMenu}: java.lang.RuntimeException: java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/MobilePauker/Fff.pau.gz (No such file or directory)
05-12 09:48:47.987 14713 14713 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4304)
05-12 09:48:47.987 14713 14713 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4347)
05-12 09:48:47.987 14713 14713 E AndroidRuntime: 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
05-12 09:48:47.987 14713 14713 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1646)
05-12 09:48:47.987 14713 14713 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
05-12 09:48:47.987 14713 14713 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
05-12 09:48:47.987 14713 14713 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6414)
05-12 09:48:47.987 14713 14713 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-12 09:48:47.987 14713 14713 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1111)
05-12 09:48:47.987 14713 14713 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:972)
05-12 09:48:47.987 14713 14713 E AndroidRuntime: Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/MobilePauker/Fff.pau.gz (No such file or directory)
05-12 09:48:47.987 14713 14713 E AndroidRuntime: 	at com.daniel.mobilepauker2.model.xmlsupport.FlashCardXMLPullFeedParser.getNextExpireDate(FlashCardXMLPullFeedParser.java:329)
05-12 09:48:47.987 14713 14713 E AndroidRuntime: 	at com.daniel.mobilepauker2.model.ModelManager.showExpireToast(ModelManager.java:483)
05-12 09:48:47.987 14713 14713 E AndroidRuntime: 	at com.daniel.mobilepauker2.activities.MainMenu.onActivityResult(MainMenu.java:273)
05-12 09:48:47.987 14713 14713 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6952)
05-12 09:48:47.987 14713 14713 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4300)```

**Comment by dfrits** [comment]
Thank you for the report. I will fix it as soon as possible

**Comment by darewealth** [comment]
The issue still persist in v2.0.0 if permission is not granted.

**Comment by dfrits** [comment]
I know. That is why i updated it to 2.0.1.
